### ISSUE TITLE
Test for Provide and Register with XUA Token and Swiss metadata 

### ISSUE THREAD

**Issue by msmock** [project-husky/husky#30]
Is there a test for Provide and Register Document Set Transaction with the Swiss EPR requirements (XUA Token, Swiss EPR Metadata)?

**Comment by ajungwirth** [comment]
Currently there are only tests without XUA token. Test with Swiss specific metadata does not exist at the moment either. [Here](https://github.com/project-husky/husky/blob/master/husky-communication/husky-communication-gen/src/test/java/org/husky/communication/integration/ConvenienceCommunicationSubmitDocumentTest.java) are all tests regarding Provide and Register Document Set Transactions.

**Comment by msmock** [comment]
Thank you. Then I will write them.

**Comment by msmock** [comment]
While trying to add a SAML Assertion to the WSS header I end up with a OpenSaml exception which reads: 

Caused by: java.lang.NullPointerException: Cannot invoke "org.opensaml.core.xml.config.XMLObjectProviderRegistry.getMarshallerFactory()" because the return value of "org.opensaml.core.config.ConfigurationService.get(java.lang.Class)" is null
	at org.opensaml.core.xml.config.XMLObjectProviderRegistrySupport.getMarshallerFactory(XMLObjectProviderRegistrySupport.java:116)
	at org.husky.xua.serialization.impl.OpenSaml2SerializerImpl.serializeToXml(OpenSaml2SerializerImpl.java:113)
	... 73 more


This is caused by a null pointer exception in ConfigurationService.get(XMLObjectProviderRegistry.class).getMarshallerFactory() which looks to me as if there is no marshaller factory is configured for opensaml in the project. 

Since the project contains no working example I'm out of ideas. Any hint?

**Comment by msmock** [comment]
Fixed by adding InitializationService.initialize(); to before method
