### ISSUE TITLE
CH-EMED-EPR: validator tries to write to home/.fhir/packages

### ISSUE THREAD

**Issue by qligier** [project-husky/husky#61]
E.g. on a Tomcat Debian:
```
java.io.FileNotFoundException: /var/lib/tomcat/.fhir/packages/packages.ini (No such file or directory)
[2023-04-24 07:41:55] [crit]     at java.base/java.io.FileOutputStream.open0(Native Method)
[2023-04-24 07:41:55] [crit]     at java.base/java.io.FileOutputStream.open(FileOutputStream.java:293)
[2023-04-24 07:41:55] [crit]     at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:235)
[2023-04-24 07:41:55] [crit]     at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:184)
[2023-04-24 07:41:55] [crit]     at org.hl7.fhir.utilities.TextFile.stringToFile(TextFile.java:122)
[2023-04-24 07:41:55] [crit]     at org.hl7.fhir.utilities.TextFile.stringToFile(TextFile.java:132)
[2023-04-24 07:41:55] [crit]     at org.hl7.fhir.utilities.npm.FilesystemPackageCacheManager.<init>(FilesystemPackageCacheManager.java:128)
[2023-04-24 07:41:55] [crit]     at org.hl7.fhir.validation.ValidationEngine.getPcm(ValidationEngine.java:976)
[2023-04-24 07:41:55] [crit]     at org.hl7.fhir.validation.ValidationEngine.initContext(ValidationEngine.java:465)
[2023-04-24 07:41:55] [crit]     at org.hl7.fhir.validation.ValidationEngine$ValidationEngineBuilder.fromNothing(ValidationEngine.java:358)
[2023-04-24 07:41:55] [crit]     at ch.ahdis.matchbox.engine.MatchboxEngine$MatchboxEngineBuilder.getEngineR4(MatchboxEngine.java:108)
[2023-04-24 07:41:55] [crit]     at org.projecthusky.fhir.emed.ch.epr.validator.ChEmedEprValidator.<init>(ChEmedEprValidator.java:51)

```

**Comment by qligier** [comment]
Currently, it is writing to `{TMP}/.fhir/packages`, so this should not be an issue anymore. It's also possible to configure the path.

https://github.com/project-husky/husky/blob/e2f733dd7bf7b59399b087702b3fcffa61da7289/husky-fhir/husky-fhir-emed-ch/husky-fhir-emed-ch-epr/src/main/java/org/projecthusky/fhir/emed/ch/epr/validator/ChEmedEprMatchboxValidator.java#L62
